server:
  port: 8081

spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5566/budgetor_ledger_db
    username: budgetor_ledger_user
    password: budgetor_ledger_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        # Enable logging of prepared statement bind parameters
        type:
          descriptor:
            sql:
              basic:
                Binder: TRACE
    com:
      budgetor:
        ledger: DEBUG
